name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '^Release ([0-9]+\.[0-9]+\.[0-9]+)'
    - name: Checkout repository
      if: ${{ steps.regex-match.outputs.match != '' }}
      uses: actions/checkout@master
    - uses: actions-ecosystem/action-push-tag@v1
      if: ${{ steps.regex-match.outputs.match != '' }}
      with:
        tag: ${{ steps.regex-match.outputs.group1 }}
    - name: Set up Node.js
      if: ${{ steps.regex-match.outputs.match != '' }}
      uses: actions/setup-node@master
      with:
        node-version: 16.0.0
    - name: Make Release Files
      if: ${{ steps.regex-match.outputs.match != '' }}
      run: |
        npm install
        npm run build
        mv build/index-linux build/hyproxy-linux && chmod +x build/hyproxy-linux
        mv build/index-macos build/hyproxy-macos && chmod +x build/hyproxy-macos
        mv build/index-win.exe build/hyproxy-win.exe
    - name: Release
      if: ${{ steps.regex-match.outputs.match != '' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.regex-match.outputs.group1 }}
        release_name: Release ${{ steps.regex-match.outputs.group1 }}
        files: |
          build/hyproxy-linux
          build/hyproxy-macos
          build/hyproxy-win.exe
